app/controllers/category_experts_controller.rb
assets/javascripts/discourse/initializers/category-experts-post-decorator.js
assets/javascripts/discourse/pre-initializers/extend-for-category-experts.js
assets/stylesheets/common.scss
config/locales/client.en.yml
config/locales/server.en.yml
config/settings.yml
lib/category_experts/post_handler.rb
plugin.rb
spec/lib/post_handler_spec.rb
spec/requests/category_experts_controller_spec.rb
test/javascripts/acceptance/category-experts-post-test.js
test/javascripts/acceptance/endorsement-checkboxes-test.js
test/javascripts/category-expert-categories.js

With `category_experts_posts_require_approval` enabled, category expert posts have this approve button
Approved posts look like this. If `category_experts_posts_require_approval` is off, category expert posts will automatically have this styling.

Display category experts posts specially

---

assets/javascripts/discourse/helpers/category-expert-question-indicator.js

@eviltrout The build fails using the `?.` operator because of uglifier. Shouldn't we be able to use it though? https://caniuse.com/?search=%3F.

Can't use JS safe navigation yet

---

assets/javascripts/discourse/components/is-question-checkbox.js
db/migrate/20210408133245_add_timestamps_to_category_experts_endorsements.rb

I like using this proc for `default` here. It's much cleaner than this
```ruby
def change
add_timestamps :category_expert_endorsements, null: true 
change_column_null :category_expert_endorsements, :created_at, false
change_column_null :category_expert_endorsements, :updated_at, false
end
```

Add timestamps to category_expert_endorsements

---

app/controllers/category_experts_controller.rb
assets/javascripts/discourse/initializers/category-experts-post-admin-menu.js
assets/stylesheets/common.scss
plugin.rb
spec/requests/category_experts_controller_spec.rb

This allows staff to mark category experts posts that were created BEFORE the category settings were configured, to be marked as "approved" category expert posts.

Allow category expert posts to be retroactively approved

---

app/controllers/category_experts_controller.rb
assets/javascripts/discourse/components/endorsement-button.js
assets/javascripts/discourse/components/endorsement-checkboxes.js
assets/javascripts/discourse/templates/components/endorsement-checkboxes.hbs
assets/javascripts/discourse/templates/modal/endorse-user.hbs
plugin.rb
spec/requests/category_experts_controller_spec.rb
test/javascripts/acceptance/endorsement-checkboxes-test.js

Right now any user can be endorsed for any category that is accepting endorsements. This was nice because it didn't require an extra call to the server, but of course cannot stand. This adds a new route that return categories that are accepting endorsements and both the logged in user, and endorsee have access to the category.

Only allow endorsement for categories that the user has access to

---

assets/javascripts/discourse/connectors/above-review-filters/endorsed-username-to-filters.hbs
assets/stylesheets/common.scss
config/locales/client.en.yml
plugin.rb

Currently, users can propose endorsement for another user. It creates a reviewable item that needs to be accepted by the admin.
When we filter by the user it returns propositions created by that specific user.
We should have another field that will allow filtering by users who will be potentially endorsed.
https://user-images.githubusercontent.com/72780/116636031-a51f7e00-a9a3-11eb-9668-074523d602b6.mov

FEATURE: filter reviewable by who was endorsed

---

app/jobs/regular/approve_past_category_expert_posts.rb
app/jobs/regular/unapprove_past_category_expert_posts.rb
config/locales/server.en.yml
config/settings.yml
lib/category_experts/post_handler.rb
plugin.rb
spec/lib/post_handler_spec.rb
spec/models/group_spec.rb

Right now, custom fields on posts and topics are saved _at the time of posting_ for category experts. This means that posts in a category by an expert, before they were in an expert group, are not marked as expert posts. The default settings capture the moment in time when the user is posting.
This setting makes it so that when you make a user a category expert, all their historical posts get the custom fields saying it's from an expert. Then to follow, then a category expert is removed as an expert, their posts _lose_ the custom fields saying they were ever from an expert.

Add site setting to approve/unapprove historical category expert posts

---

app/controllers/category_experts_controller.rb
spec/requests/category_experts_controller_spec.rb

`category_accepting_endorsements` setting has string values like "true" or "false". Even though it was registered as :boolean because column in database is a string:
`register_category_custom_field_type(CategoryExperts::CATEGORY_ACCEPTING_ENDORSEMENTS, :boolean)`
Comparing <> "" was not enough to ensure that `category_accepting_endorsements` is checked
In spec I just added new category with "false" to ensure it is not added
to endorsable categories.

FIX: correct return of endorsable categories

---

lib/category_experts/post_handler.rb
spec/lib/post_handler_spec.rb

Bug was introduced here https://github.com/discourse/discourse-category-experts/commit/dd7fbd2f0999adf3fee234119ac299839816abb4#diff-040b0c3e0e3b0c377ccb9da72d51e1a9716135b8958e74aa81f104651972ee23R112
When private message is sent there is no category and this code was crashing

FIX: do not error when private message is sent

---

plugin.rb

plugin-api's `on` prevents the hook from being called when the plugin is disabled

FIX: Don't run event hooks when plugin is disabled

---

assets/javascripts/discourse/components/category-experts-settings.js
assets/javascripts/discourse/templates/components/category-experts-settings.hbs

This mirrors the way the create-invite modal fetches all groups.

FIX: Fetch all groups for group-chooser in category settings

---

app/serializers/reviewable_category_expert_suggestion_serializer.rb

The front-end reviewable model converts `category_id` to a full-on category model, so no need to serialize `category`. Also, `category_id` and `include_category_id?` are defined on the base `ReviewableSerializer`, so have to override both those methods for this reviewable.
This category link is broken right now, but look here! It's fixed!

FIX: Category link in reviewable

---

spec/models/reviewable_category_expert_suggestion_spec.rb

As we’re going to use `ActiveRecord` enums instead of our current custom ones in core, we need to update some of the specs of this plugin otherwise they will break with the new changes.
(PR for core: https://github.com/discourse/discourse/pull/15330)

DEV: Make specs a bit less brittle

---

assets/javascripts/discourse/connectors/advanced-search-options-below/category-experts-search-fields.hbs

Core's defaults are changing in https://github.com/discourse/discourse/pull/13685. This commit ensures the behaviour of this plugin will not change.

DEV: Update plugin-outlet arguments

---

test/javascripts/helpers/category-experts-pretender.js

This PR registers a default pretender for the `/category-experts/retroactive-approval/:post_id` endpoint which is added by this plugin and gets called when the post actions list is expanded. Without this default pretender, acceptance tests of other plugins that expand the post actions list will fail if this plugin is installed because there is nothing to handle the HTTP request made by this plugin.

DEV: Create pretender for the `/category-experts/retroactive-approval/:post_id` endpoint

---

assets/javascripts/discourse/components/category-experts-settings.js
assets/javascripts/discourse/templates/components/category-experts-settings.hbs
assets/stylesheets/common.scss
config/locales/client.en.yml
lib/category_experts/post_handler.rb
plugin.rb
spec/lib/post_handler_spec.rb

There was a request to have topic automatically tagged with a specific tag, when a post has an approved category expert post. This adds a setting in the category configuration for category experts, to specify the tag.
-4e9c-99d5-49df240c3355)

FEATURE: Auto-tagging topics when experts post

---

assets/javascripts/discourse/helpers/category-expert-topic-list-indicators.js
config/locales/server.en.yml
config/settings.yml
lib/category_experts/post_handler.rb
spec/jobs/correct_historical_category_expert_posts_spec.rb
spec/lib/post_handler_spec.rb
spec/models/group_spec.rb
spec/requests/category_experts_controller_spec.rb

adds site setting, `first_post_can_be_considered_expert_post`, which defaults to false.
left as default, this setting prevents the situation of an expert posting a topic that is immediately marked as having an "expert response", despite there being no replies at all, let alone an expert reply.
details: https://dev.discourse.org/t/sailpoint-category-experts-exclude-first-poster/105541

Add setting to include/exclude OP when adding Expert highlighting.

---

assets/javascripts/discourse/components/modal/expert-group-chooser.js
spec/fabricators/category_expert_fabricators.rb
spec/system/reviewable_category_expert_suggestion_spec.rb

Since a04991e0a2370f65c5d22a4c7f8b10e6b569b235 the
approval/confirmation button in the Approve action for
category expert endorsements has been broken; this.action
was used instead of this.args.model.action.
This commit fixes the issue and adds initial system specs
for the category experts functionality.

FIX: Category expert approval in modal

---

config/locales/client.en.yml
spec/system/reviewable_category_expert_suggestion_spec.rb

This system test is failing in core after some changes to the review queue.
This PR fixes that by relying on the text of the button instead of a class name. This should be backwards compatible since the content hasn't change, and arguably a little bit more clear and a little bit more stable than relying on the class name.

FIX: Amend failing reviewable system test selector

---

assets/javascripts/discourse/components/modal/endorse-user/endorsement-checkboxes.hbs
assets/javascripts/discourse/components/reviewable-category-expert-suggestion.js
assets/javascripts/discourse/components/reviewable-category-expert-suggestions.js

Before: Endorsement reviewable had an interface error: 
After: It shows relevant information:
Before: The checkbox on Endorse User modal did not show the click state:
After: It shows click state:

FIX: Endorsement reviewable text & endorsement checkboxes

---

assets/stylesheets/common.scss

Before: There was no space after "Close":
After: Added space after "Close":

UX: Add Space between 'Close' and 'Ask a category expert to respond

---

config/locales/client.en.yml
lib/category_experts/outgoing_web_hook_extension.rb
lib/category_experts/post_handler.rb
plugin.rb
spec/fabricators/outgoing_category_experts_web_hook_fabricator.rb
spec/lib/post_handler_spec.rb

This PR is adding a WebHook Event for the post that is approved by the Category Experts.
This is the screenshot for the Category Experts approved webhook event option:
And this is the screenshot for the Webbhook events after the post got approved by a Category Expert:

FEATURE: Added Category Experts approved WebHook Event

---

lib/category_experts/outgoing_web_hook_extension.rb
spec/lib/post_handler_spec.rb

Approved post Webhook event payload header will have 'X-Discourse-Event-Type: post':

DEV: Approved Post Webhook Event Payload Update

---

config/locales/client.en.yml

The PR is deleting deprecated codes from the updates on the post approved webhook event.

DEV: Deleting deprecated codes

---

lib/category_experts/post_handler.rb
plugin.rb
spec/fabricators/outgoing_category_experts_web_hook_fabricator.rb
spec/lib/post_handler_spec.rb

This PR is adding a WebHook Event for the post that is approved by the Category Experts.
This is the screenshot for the Category Experts approved webhook event option:

FEATURE: Added Category Experts unapproved post WebHook Event

---

app/controllers/category_experts_controller.rb
lib/category_experts/post_handler.rb
spec/lib/post_handler_spec.rb

This PR is to fix the issue when a new post is created, it sends a `category-experts unapproved post` webhook event.
Check if it is a new post and does not send `category-experts unapproved post` webhook event.

FIX: new post sending unapproved post webhook event

---

config/locales/client.en.yml
db/fixtures/007_category_experts_web_hook_event_types.rb
plugin.rb

This PR adds Category Experts webhook events types:

FEATURE: Add Category-Experts webhook event types

---

.discourse-compatibility
assets/javascripts/discourse/initializers/category-experts-post-decorator.js

This PR updates deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: Update deprecated Font Awesome icon names

---

lib/category_experts/post_handler.rb
plugin.rb
spec/plugin_spec.rb

Currently we don't adjust category-experts custom fields when a post is moved. This is not good! This PR adds a listener for `post_moved` event, and adjusts post and topic custom fields correclty.
The tests look insane here, but hey, category experts is just.. a bunch of custom fields..

FEATURE: Support custom field correcting on post_move

---

assets/javascripts/discourse/components/category-experts-settings.gjs

Replace `filterBy` with an explicit `filter` function for clarity and consistency. This change ensures improved readability and aligns with modern code practices without altering functionality.

DEV: Replace deprecated Ember's array `filterBy` with `filter`
