discourse/discourse-category-experts

- assets/javascripts/discourse/connectors/advanced-search-options-below/category-experts-search-fields.hbs
- assets/javascripts/discourse/initializers/category-experts-search.js
- config/locales/client.en.yml
- plugin.rb
> Advanced Search filters and UI

- plugin.rb
Also there were old routes that I removed, but I guess never removed from the actual rails routes
> Only mark as question if post is the first post

- assets/javascripts/discourse/initializers/category-experts-post-admin-menu.js
@CvX Your PR made me see this code that I had missed. Once this is merged, your PR will have to change a bit because it changes a function name, but I'll show you in the review
> Remove debugging code

- assets/javascripts/discourse/initializers/category-experts-search.js
- assets/stylesheets/common.scss
> Align advanced search filters

- lib/category_experts/post_handler.rb
- spec/lib/post_handler_spec.rb
- spec/requests/category_experts_controller_spec.rb
First post should not be automatically approved
> FEATURE: do not automatically approve first post

- plugin.rb
Add count of posts for each expert group to the serializer.
> FEATURE: add post count to serializer

- lib/category_experts/post_handler.rb
- spec/lib/post_handler_spec.rb
- spec/requests/category_experts_controller_spec.rb
Reverts discourse/discourse-category-experts#33
> Revert "FEATURE: do not automatically approve first post"

- assets/javascripts/discourse/connectors/above-review-filters/endorsed-username-to-filters.hbs
- assets/javascripts/discourse/connectors/above-review-filters/endorsed-username-to-filters.js
Deprecated in https://github.com/discourse/discourse/pull/12042
> DEV: Replace a deprecated component

- assets/javascripts/discourse/initializers/category-experts-post-decorator.js
- test/javascripts/acceptance/category-experts-post-test.js
The post model is not always defined and that caused page to stop
loading.
> FIX: Allow filter by user when plugin is enabled

- Gemfile.lock
- spec/lib/post_handler_spec.rb
- spec/models/group_spec.rb
- spec/requests/category_experts_controller_spec.rb
Updates rubocop-discourse version
> DEV: Bump rubocop-discourse

- .github/workflows/plugin-linting.yml
- .github/workflows/plugin-tests.yml
- .rubocop.yml
- .streerc
- Gemfile
- Gemfile.lock
- app/controllers/category_experts_controller.rb
- app/jobs/regular/approve_past_category_expert_posts.rb
- app/jobs/regular/correct_historical_category_expert_posts.rb
- app/jobs/regular/unapprove_past_category_expert_posts.rb
- app/jobs/scheduled/remind_admin_of_category_experts_posts_job.rb
- app/jobs/scheduled/remind_category_experts_job.rb
- app/models/category_expert_endorsement.rb
- app/models/reviewable_category_expert_suggestion.rb
- app/serializers/reviewable_category_expert_suggestion_serializer.rb
- db/migrate/20210225181416_create_category_expert_endorsements.rb
- db/migrate/20210408133245_add_timestamps_to_category_experts_endorsements.rb
- db/migrate/20210614050646_change_boolean_custom_fields_to_ints.rb
- lib/category_experts/endorsement_rate_limiter.rb
- lib/category_experts/post_handler.rb
- plugin.rb
- spec/jobs/correct_historical_category_expert_posts_spec.rb
- spec/jobs/remind_admin_of_category_expert_posts_job_spec.rb
- spec/jobs/remind_category_experts_job_spec.rb
- spec/jobs/unapprove_past_category_expert_posts_spec.rb
- spec/lib/post_handler_spec.rb
- spec/models/category_expert_endorsement_spec.rb
- spec/models/group_spec.rb
- spec/models/reviewable_category_expert_suggestion_spec.rb
- spec/requests/category_experts_controller_spec.rb
Adds syntax_tree configuration and formats code
> DEV: Introduce syntax_tree for ruby formatting

- spec/requests/category_experts_controller_spec.rb
c.f. https://github.com/discourse/discourse/pull/22103
> DEV: Remove usages of RateLimiter.clear_all!

- spec/system/reviewable_category_expert_suggestion_spec.rb
cc: @Drenmi @martin-brennan (see: https://github.com/discourse/discourse/actions/runs/6151101938/job/16690479535)
> DEV: Skip a flaky spec

- spec/jobs/remove_expert_post_properties_from_first_posts_spec.rb
- spec/lib/post_handler_spec.rb
Needed to fix specs in https://github.com/discourse/discourse/pull/24357
> DEV: Use refresh_auto_groups to fix specs

- spec/models/group_spec.rb
Needed to fix specs in https://github.com/discourse/discourse/pull/24357
> DEV: More refresh_auto_groups to fix specs

- app/jobs/scheduled/remind_admin_of_category_experts_posts_job.rb
- app/jobs/scheduled/remind_category_experts_job.rb
- config/settings.yml
- spec/jobs/remind_admin_of_category_expert_posts_job_spec.rb
- spec/jobs/remind_category_experts_job_spec.rb
Marking the tests as pending until a fix can be made.
> DEV: TOPIC_NEEDS_EXPERT_POST_APPROVAL is no longer a boolean

- test/javascripts/acceptance/endorsement-checkboxes-test.js
https://github.com/discourse/discourse/pull/27964
> DEV: Fix acceptance test when using the new topic map

- assets/javascripts/discourse/components/category-experts-approve-button.gjs
- assets/javascripts/discourse/components/category-experts-unapprove-button.gjs
- assets/javascripts/discourse/initializers/category-experts-post-decorator.js
- test/javascripts/acceptance/category-experts-post-widget-post-menu-test.js
Requires https://github.com/discourse/discourse/pull/28670
> DEV: Added compatibility with the Glimmer Post Menu

- app/models/reviewable_category_expert_suggestion.rb
- spec/system/reviewable_category_expert_suggestion_spec.rb
See https://github.com/discourse/discourse/pull/29981
> DEV: Fix spec following core change

- lib/category_experts/post_handler.rb
- plugin.rb
- spec/lib/post_handler_spec.rb
This PR updates the category experts custom fields when post owner changed.
> DEV: Handle post owner changed case
